### ISSUE TITLE
uri does work as a source by providing its dimensions as well

### ISSUE THREAD

**Issue by gorvinsky** [MiLeung/rn-sprite-sheet#11]
In the documentations, it is stated that { uri } will not work as a source. However, it's not entirely true. It will work if you provide its dimentions as well. Refer below for more info.

This will not work:
```
source = { uri: 'someurl' };
```
This will work:
```
source = { uri: 'someurl', width: 100, height: 100 };
```

Do correct me if I'm wrong.

**Comment by MiLeung** [comment]
You are correct if `resolveAsset` can parse the `height` and `width` properties. https://github.com/MiLeung/rn-sprite-sheet/blob/master/src/SpriteSheet.js#L44

So you have a working example using `source = { uri: 'someurl', width: 100, height: 100 };`?

**Comment by gorvinsky** [comment]
@MiLeung I've been using it yes.

**Comment by MiLeung** [comment]
Nice, can you please update the README and create a PR for this?

**Comment by gorvinsky** [comment]
> Nice, can you please update the README and create a PR for this?

Done.

**Comment by MiLeung** [comment]
Thank you!

**Comment by gorvinsky** [comment]
> Thank you!

@MiLeung Sorry, I just recall that the proptypes of source is currently set to `PropTypes.number.isRequired`. You may want to change it to `PropTypes.any.isRequired` for it to work properly.
