### ISSUE TITLE
[Feature] Autoplay

### ISSUE THREAD

**Issue by JeffGuKang** [MiLeung/rn-sprite-sheet#19]
`Autoplay` will be useful as below. 
Sometimes I just want to play animation without control the `SpriteSheet` by ref. 

```js
<SpriteSheet
  {...props}
  animations={{
      basic: [0, 1, 2, 3],
  }},
  autoplay={'basic'}
/>
```

**Comment by elisechant** [comment]
Although that would be a simple feature to add, I still think it is better for the app to control the play behaviour.  

I also think it would better to make the component "autoplay" once the _whole View_ has been mounted not just the SpriteSheet component. 

 You can implement this with Hooks such as:

```
import React, { useRef, useEffect}  from 'react';

const MyView = () => {
  const elSlider = useRef(null);

  useEffect(() => {
    slider.current.play('basic');
  }, []);

  return (
    <View>
      <SpriteSheet ref={elSlider} 
```

**Comment by JeffGuKang** [comment]
> Although that would be a simple feature to add, I still think it is better for the app to control the play behaviour.
> 
> I also think it would better to make the component "autoplay" once the _whole View_ has been mounted not just the SpriteSheet component.
> 
> You could implement this with Hooks such as:
> 
> ```
> import React, { useRef, useEffect}  from 'react';
> import SpriteSheet from "rn-sprite-sheet";
> 
> const MyView = () => {
>   const elSlider = useRef(null);
> 
>   useEffect(() => {
>     elSlider.current.play({ type: 'basic'});
>   }, []);
> 
>   return (
>     <View>
>       <SpriteSheet ref={elSlider} 
> ```

I agree with you. I am using the way now.
