### ISSUE TITLE
Calculation for animation doesn't seem to work correctly

### ISSUE THREAD

**Issue by lucasbento** [MiLeung/rn-sprite-sheet#2]
I'm trying to use a sprite with donuts, it has 8 columns, 3 rows and 23 donuts, each sized 200x200:

```jsx
        <RNSpriteSheet
          ref={ref => this.spriteSheet = ref}
          source={require('../../../assets/images/spritesheets/pinkDonut.png')}
          columns={8}
          rows={3}
          width={200}
          animations={{
            show: [...new Array(23)].map((i, key) => key),
          }}
        />
```

And I'm triggering `play` like this:

```jsx
componentDidMount() {
    this.spriteSheet.play({
      type: 'show',
      fps: 14,
      loop: true,
      resetAfterFinish: true,
    });
}
```

But the transition between them isn't working as expected:

![kapture 2018-03-01 at 14 23 21](https://user-images.githubusercontent.com/6207220/36846747-28fb3d36-1d5c-11e8-8dc0-4d2991d3ab49.gif)

@MiLeung: is there anything that I can do to get it working?

**Comment by MiLeung** [comment]
Does your sprite sheet have equal padding (or lack of padding) around each image? If each frame is 200x200 on an 8x3 grid, the sprite sheet image should be 1600x600. Is this the case? I am using [resolveAssetSource](https://github.com/MiLeung/rn-sprite-sheet/blob/master/src/SpriteSheet.js#L48) to get the image dimensions and using the height or width prop to calculate the other dimension (width or height) and it looks like there might be some extra vertical padding on your sprite sheet image.

**Comment by lucasbento** [comment]
@MiLeung: yeah, the spritesheet was wrong, thank you for the prompt response!
