### ISSUE TITLE
Image downsampling on Android by fresco

### ISSUE THREAD

**Issue by JeffGuKang** [MiLeung/rn-sprite-sheet#24]
https://github.com/facebook/fresco/issues/2397

Images are downsampled when loading large bundled images on Android. And normally sprite sheet are using large images. 
And I am using facebook/fresco bundle I patched to avoid downsampling. But I do not want to patch fesco for some reasons. 

Is there anybody to solve this issue?

**Comment by MiLeung** [comment]
Not sure, maybe break up your sprite sheet into smaller sprite sheets?

**Comment by JeffGuKang** [comment]
> Not sure, maybe break up your sprite sheet into smaller sprite sheets?
I hope facebook/fresco to have image quality options.
Temprorily JPEG type can be the substitute. But not tried.
