### ISSUE TITLE
Not usable native method argument error in v1.1.10 

### ISSUE THREAD

**Issue by JeffGuKang** [MiLeung/rn-sprite-sheet#27]
![image](https://user-images.githubusercontent.com/216363/92547533-074e3600-f290-11ea-8d9d-96ead4391890.png)

It occurs after changing the version from 1.1.9 to 1.1.10.

**Comment by Solid-Metal** [comment]
same

**Comment by MiLeung** [comment]
I don't have time to maintain this package, so it is up to the community to make a PR. Sorry about that.

**Comment by Solid-Metal** [comment]
understood, but for now the workaround is to put offsetx and offsety on the props
