### ISSUE TITLE
Offer to continue this project

### ISSUE THREAD

**Issue by AllBitsEqual** [MiLeung/rn-sprite-sheet#31]
Hi Michael, I wasn't able to find an easier way to contact you so I'll do it here.

I'm currently in the process of preparing a small number of useful React Native Packages and while I originally planned to use rn-sprite-sheet in my own projects, it turns out that to achieve my goals and full compatibility with current versions of React Native and React Web at the same time (for example using EXPO) some adjustments are needed.

I would offer to keep working on the project, keep it downwards compatible and also adding new features in a "non breaking change" way so people that previously used rn-sprite-sheet could switch over to my version and use their existing implementations without any changes needed to ease/help their migration.

If you are interested in this and would like to discuss details, feel free to contact me on twitter (https://twitter.com/AllBitsEqual) or discord (AllBitsEqual#2341)

**Comment by mileung** [comment]
Sure we can work something out. I don't use social media, so email me@mileung.com and we can chat from there.

**Comment by AllBitsEqual** [comment]
Done, thx
