### ISSUE TITLE
With 10x10 Sprite Sheet, Animation Looks Crisp On iOS But Looks Very Very Pixelated On Android

### ISSUE THREAD

**Issue by mikeyamato** [MiLeung/rn-sprite-sheet#6]
Has anyone else experienced this issue? I'm trying to understand what can be causing this huge drop in resolution. Everything else on the screen surrounding the sprite (text, images, & buttons) looks good. Just the sprite is pixelated. 

Here's my code for `SpriteSheet`. 

    <SpriteSheet 
        ref={ref => (this.animation = ref)}
        source={require('./animation.png')}
        columns={10}
        rows={10}
        animations={{
          open: Array.from({ length: 100 }, (map, value) => value), 
        }}
        viewStyle={{   
          marginTop: '25%'
          alignSelf: 'center',
          marginBottom: '16.3%',
        }} 
        width={'150%'}  // setting this to 100% doesn't change the pixelation issue
    />

**Comment by MiLeung** [comment]
This package does not do any image processing and simply relies on an `Animated.Image`, so I'd be surprised if this package is responsible for the differences in image quality. Can you render the sprite sheet by itself in an `Image` on both platforms properly?

**Comment by mikeyamato** [comment]
So in iOS the sprite sheet renders clearly as a static image. But on Android, I once again have the pixelated issue. So this means that the sprite sheet itself is the culprit? I have zero idea why this is happening but further investigation on my end is needed. What's weird is that nothing else in my app is pixelated.

BTW the devices I'm testing this on are iPhone X and Galaxy S8. 

@MiLeung, can you keep this issue open a bit longer? If I can find a solution I'll add it in.

**Comment by MiLeung** [comment]
Sure.

I think your image isn't big enough. Maybe iOS has anti-aliasing whereas Android does not.

**Comment by mikeyamato** [comment]
@MiLeung please go ahead and close this issue.

Unfortunately I have not found a solution to my issue. Using [TexturePacker](https://www.codeandweb.com/texturepacker) and creating sprite sheets in various resolution sizes didn't work. Scaling my 10x10 sprite sheet 2x (19900x5860) and 3x (29850x8790) the resolution still yielded a very pixelated animation. I also tried tweaking the settings but that too had no affect on the visuals. I'll still use your package for iOS since there's no issue there but for Android I had to jury-rig something to fake an animation without the use of a sprite.

In case anyone sees this entry after the fact below are my specs.
```
react: 16.6.3
react-native: 0.57.8
rn-sprite-sheet: ^1.1.1
```

**Comment by MiLeung** [comment]
Interesting... alrighty

**Comment by ev01ve** [comment]
I'm having the same problem.  I think this is the source of the problem: https://github.com/facebook/react-native/issues/21301

**Comment by ev01ve** [comment]
I'm having the same issue.  I think this is the cause: https://github.com/facebook/react-native/issues/21301

**Comment by liCat** [comment]
I have the same issue.  and maybe I will  give up rn-sprite-sheet, then **split** the large image to small.

**Comment by MiLeung** [comment]
I think this is not an issue with rn-sprite-sheet, but rather React Native itself.
