### ISSUE TITLE
Not staying on last frame when "resetAfterFinish" is set to false

### ISSUE THREAD

**Issue by murilobast** [MiLeung/rn-sprite-sheet#8]
When using "resetAfterFinish: false" the animation resets to first frame instead of staying on last.

Ex:
``` js
spriteRef.current.play({
	fps: 8,
	type: 'death',
	resetAfterFinish: false,
	loop: false
})
```

The result is the animation playing backwards

**Comment by murilobast** [comment]
NVM, found the issue. The problem is that I was flipping the image on "imageStyle" and that inverted the animation order

``` js
imageStyle={{
	transform: [
	{ scaleX: !player ? -1 : 1 }
}}
```

**Comment by MiLeung** [comment]
You could also apply the scaleX to viewStyle so the frame order doesn't reverse.

**Comment by murilobast** [comment]
> You could also apply the scaleX to viewStyle so the frame order doesn't reverse.

That's exactly what I did. Everything is working fine 👍
